/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'phone' : string,
}
export interface CustomerInquiry {
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'customerAddress' : string,
  'totalAmount' : bigint,
  'customerId' : [] | [bigint],
  'items' : Array<OrderItem>,
  'upiTransactionRef' : string,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'requiresPrescription' : boolean,
  'sellerId' : [] | [string],
  'image' : ExternalBlob,
  'price' : bigint,
  'medicineType' : string,
}
export interface Refund {
  'status' : string,
  'refundId' : bigint,
  'orderId' : bigint,
  'timestamp' : bigint,
  'amount' : bigint,
  'reason' : string,
}
export interface SellerPublic {
  'id' : string,
  'medicalLicenseNumber' : string,
  'ownerName' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'email' : string,
  'storeName' : string,
  'panNumber' : string,
  'aadhaarNumber' : string,
  'phone' : string,
  'verificationStatus' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      ExternalBlob,
      bigint,
      boolean,
      string,
      boolean,
    ],
    bigint
  >,
  'addSellerProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      string,
      ExternalBlob,
      bigint,
      boolean,
      string,
      boolean,
    ],
    bigint
  >,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'customerLogin' : ActorMethod<[string, string], bigint>,
  'customerRegister' : ActorMethod<[string, string, string, string], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteSellerProduct' : ActorMethod<[string, string, bigint], undefined>,
  'generateOtp' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getCustomerById' : ActorMethod<[bigint], Customer>,
  'getInquiries' : ActorMethod<[], Array<CustomerInquiry>>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getRefunds' : ActorMethod<[], Array<Refund>>,
  'getSellerById' : ActorMethod<[string], [] | [SellerPublic]>,
  'getSellerDashboard' : ActorMethod<[string, string], string>,
  'getSellerOrders' : ActorMethod<[string, string], Array<Order>>,
  'getSellerProducts' : ActorMethod<[string], Array<Product>>,
  'getSellers' : ActorMethod<[], Array<SellerPublic>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdminLoggedIn' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCustomerLoggedIn' : ActorMethod<[bigint], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>, bigint, string],
    bigint
  >,
  'placeOrderWithCustomer' : ActorMethod<
    [bigint, Array<OrderItem>, bigint, string],
    bigint
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestRefund' : ActorMethod<[bigint, string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sellerLogin' : ActorMethod<[string, string], boolean>,
  'sellerRegister' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    string
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitInquiry' : ActorMethod<[string, string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProductWithImage' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      ExternalBlob,
      bigint,
      boolean,
      string,
      boolean,
    ],
    undefined
  >,
  'updateRefundStatus' : ActorMethod<[bigint, string], undefined>,
  'updateSellerProductWithImage' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      bigint,
      string,
      ExternalBlob,
      bigint,
      boolean,
      string,
      boolean,
    ],
    undefined
  >,
  'updateSellerVerificationStatus' : ActorMethod<[string, string], undefined>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];