/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CustomerInquiry = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'customerPhone' : IDL.Text,
  'createdAt' : IDL.Int,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(OrderItem),
  'upiTransactionRef' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'requiresPrescription' : IDL.Bool,
  'sellerId' : IDL.Opt(IDL.Text),
  'image' : ExternalBlob,
  'price' : IDL.Nat,
  'medicineType' : IDL.Text,
});
export const Refund = IDL.Record({
  'status' : IDL.Text,
  'refundId' : IDL.Nat,
  'orderId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'reason' : IDL.Text,
});
export const SellerPublic = IDL.Record({
  'id' : IDL.Text,
  'medicalLicenseNumber' : IDL.Text,
  'ownerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'storeName' : IDL.Text,
  'panNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'phone' : IDL.Text,
  'verificationStatus' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        ExternalBlob,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'addSellerProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        ExternalBlob,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'customerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'customerRegister' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteSellerProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCustomerById' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getRefunds' : IDL.Func([], [IDL.Vec(Refund)], ['query']),
  'getSellerById' : IDL.Func([IDL.Text], [IDL.Opt(SellerPublic)], ['query']),
  'getSellerDashboard' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'getSellerOrders' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getSellerProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getSellers' : IDL.Func([], [IDL.Vec(SellerPublic)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminLoggedIn' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isCustomerLoggedIn' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'placeOrderWithCustomer' : IDL.Func(
      [IDL.Nat, IDL.Vec(OrderItem), IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'requestRefund' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sellerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'sellerRegister' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProductWithImage' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        ExternalBlob,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateRefundStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateSellerProductWithImage' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        ExternalBlob,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateSellerVerificationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CustomerInquiry = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'customerPhone' : IDL.Text,
    'createdAt' : IDL.Int,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(OrderItem),
    'upiTransactionRef' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'requiresPrescription' : IDL.Bool,
    'sellerId' : IDL.Opt(IDL.Text),
    'image' : ExternalBlob,
    'price' : IDL.Nat,
    'medicineType' : IDL.Text,
  });
  const Refund = IDL.Record({
    'status' : IDL.Text,
    'refundId' : IDL.Nat,
    'orderId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const SellerPublic = IDL.Record({
    'id' : IDL.Text,
    'medicalLicenseNumber' : IDL.Text,
    'ownerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'storeName' : IDL.Text,
    'panNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'phone' : IDL.Text,
    'verificationStatus' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          ExternalBlob,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'addSellerProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          ExternalBlob,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'customerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'customerRegister' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteSellerProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCustomerById' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getRefunds' : IDL.Func([], [IDL.Vec(Refund)], ['query']),
    'getSellerById' : IDL.Func([IDL.Text], [IDL.Opt(SellerPublic)], ['query']),
    'getSellerDashboard' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        ['query'],
      ),
    'getSellerOrders' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getSellerProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getSellers' : IDL.Func([], [IDL.Vec(SellerPublic)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminLoggedIn' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isCustomerLoggedIn' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'placeOrderWithCustomer' : IDL.Func(
        [IDL.Nat, IDL.Vec(OrderItem), IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'requestRefund' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sellerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'sellerRegister' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProductWithImage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          ExternalBlob,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateRefundStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateSellerProductWithImage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          ExternalBlob,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateSellerVerificationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };